base: &base
  adapter: postgresql
  encoding: utf8
  username: postgres
  password: test
  host: localhost
  pool: 5

development:
  <<: *base
  database: cerebro_api_development

production:
  <<: *base
  database: cerebro_api_production