# config/secrets.yml
defaults: &defaults
  devise_pepper: 'xxxxxxx'
  devise_secret_key: 'xxxxxxx'
  secret_key_base: 2460f7607b3284b13c777eb4f13bbb5a3827e09391fee7dd1e0cc424543b95d9b63af7db584f1f505abfaa28c5278e57f071c1694ff2cc9befe5f7be28dde784


secured: &secured
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults
  <<: *secured

production:
  <<: *defaults
  <<: *secured
